import {createReportPDF} from './report-pdf';
// Escape all company input and generated prose before inserting it into a document.
export const escapeReportText=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const e=escapeReportText;
const paragraph=text=>text?`<p>${e(text)}</p>`:'';
const block=(label,text)=>text?`<div class="detail"><h4>${e(label)}</h4>${paragraph(text)}</div>`:'';
const list=items=>items?.length?`<ul>${items.map(item=>`<li>${e(item)}</li>`).join('')}</ul>`:'';
export function renderReport({name,summary,formula,notice,attributes=[],feedback=[],issues=[],questions=[],sources=[],metadata=[]}){
 const open=issues.filter(issue=>!issue.done),closed=issues.filter(issue=>issue.done);
 const agenda=items=>items.map((item,index)=>`<article class="agenda"><span class="number">${String(index+1).padStart(2,'0')}</span><div><h3>${e(item.agenda)}</h3>${block('Proposed lead',item.lead)}${block('Expected meeting output',item.outcome)}${block('Meeting note',item.note)}<p class="muted">From the issue · ${e(item.title)}</p></div></article>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(name)} · Metric Lab</title><style>
 *{box-sizing:border-box}body{margin:0;background:#edf0f4;color:#192d40;font:16px/1.6 Arial,Helvetica,sans-serif}.sheet{max-width:960px;margin:36px auto;background:#fff;padding:56px 64px;border-top:7px solid #d65a32}.brand{font-size:22px;font-weight:bold;letter-spacing:-.6px}.brand span{color:#d65a32}.eyebrow{color:#97502e;font-size:12px;font-weight:bold;text-transform:uppercase;letter-spacing:1.8px;margin-top:32px}h1{font-family:Georgia,serif;font-size:36px;line-height:1.2;margin:12px 0 20px}h2{font-size:23px;line-height:1.3;margin:0 0 20px}h3{font-size:18px;line-height:1.4;margin:0 0 8px}h4{font-size:13px;margin:12px 0 4px}p{margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere}.formula{padding:18px 22px;background:#172c40;color:white;border-radius:6px;margin:24px 0}.summary{display:flex;gap:24px;padding:15px 0;border-block:1px solid #dce2e8}.summary strong{font-size:24px}.muted,footer{color:#617082;font-size:13px}section{margin-top:38px}.agenda{display:flex;gap:18px;padding:22px 0;border-bottom:1px solid #dce2e8;break-inside:avoid}.number{color:#b34d2f;font:28px Georgia,serif}.card{padding:20px;border:1px solid #dce2e8;border-radius:8px;margin:14px 0;break-inside:avoid}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid .card{margin:0}.classification{font-weight:bold;color:#934529}.tag{display:inline-block;background:#eef0f2;padding:5px 9px;border-radius:5px;font-size:12px;margin:5px 5px 5px 0}.solution{border-left:3px solid #36816c;background:#f0f6f3;padding:12px 18px;margin-top:18px}.feedback{background:#f4f5f7;padding:12px 16px;margin-top:10px;border-radius:5px}.notice{background:#f5f7fa;padding:16px 20px;font-size:14px;margin-top:20px}ul{padding-left:22px}li{overflow-wrap:anywhere}footer{margin-top:40px;padding-top:20px;border-top:1px solid #dce2e8}@media(max-width:650px){.sheet{margin:0;padding:26px 20px}.grid{grid-template-columns:1fr}h1{font-size:29px}}@media print{@page{size:A4;margin:16mm}body{background:white;font-size:10pt}.sheet{margin:0;padding:0;max-width:none;border-top:4px solid #d65a32}h1{font-size:26pt}.grid{display:block}.grid .card{margin-bottom:12px}.screen-note{display:none}h2,h3{break-after:avoid}section{margin-top:24px}a{color:inherit}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
 </style></head><body><main class="sheet"><header><div class="brand">≋ Metric <span>Lab</span></div><p class="eyebrow">Assessment & meeting agenda</p><h1>${e(name)}</h1>${paragraph(summary)}<div class="formula">${e(formula)}</div><div class="summary"><div><strong>${open.length}</strong> open items</div><div><strong>${closed.length}</strong> resolved</div><div><strong>${attributes.length}</strong> attributes</div></div><p class="muted screen-note">Open this document in your browser. Use Print → Save as PDF for a PDF copy.</p></header>
 <section><p class="eyebrow">01 · Prepare the meeting</p><h2>Your open agenda</h2>${open.length?agenda(open):paragraph('No open agenda items. Recorded resolutions do not establish that the metric is valid.')}</section>
 ${closed.length?`<section><h2>Recorded resolutions</h2>${closed.map(item=>`<article class="card"><span class="tag">Resolved</span><h3>${e(item.title)}</h3>${block('Recorded resolution',item.note)}${block('Original agenda item',item.agenda)}</article>`).join('')}</section>`:''}
 <section><p class="eyebrow">02 · Examine the metric</p><h2>Nine-attribute assessment</h2><div class="grid">${attributes.map(attr=>`<article class="card"><h3>${e(attr.name)}</h3><p class="classification">${e(attr.classification)}</p>${paragraph(attr.reasoning)}${block('Conditions',attr.conditions)}${block('Additional interpretation',attr.interpretation)}${block('Missing evidence',attr.missing)}${(attr.roles||[]).map(role=>block(role.name,role.text)).join('')}${block('Evidence references',attr.evidence)}</article>`).join('')}</div></section>
 ${feedback.length?`<section><h2>Feedback supplied for discussion</h2>${feedback.map(role=>`<div class="feedback"><h3>${e(role.name)}</h3>${paragraph(role.text||'Not supplied')}</div>`).join('')}</section>`:''}
 <section><p class="eyebrow">03 · From discussion to action</p><h2>Issues and proposed resolutions</h2>${issues.map(item=>`<article class="card"><h3>${e(item.title)}</h3>${(item.attributes||[]).map(name=>`<span class="tag">${e(name)}</span>`).join('')}${block('Why it matters',item.reasoning)}${(item.roles||[]).map(role=>`<div class="feedback"><h4>${e(role.name)}</h4>${paragraph(role.text)}</div>`).join('')}<div class="solution">${block('Proposed resolution',item.solution)}${block('Agenda item',item.agenda)}${block('Expected meeting output',item.outcome)}</div>${block('Evidence references',item.evidence)}</article>`).join('')}</section>
 ${questions.length?`<section><h2>Questions still to clarify</h2>${list(questions)}</section>`:''}
 <section><h2>Research evidence and limits</h2><div class="notice">${paragraph(notice)}</div>${sources.map(source=>`<div class="detail"><h4>${e(source.id)}</h4>${paragraph(source.text)}</div>`).join('')}</section><footer>Metric Lab · ${e(new Date().toLocaleDateString('en-GB',{year:'numeric',month:'long',day:'numeric'}))}${metadata.map(item=>paragraph(item)).join('')}</footer></main></body></html>`;
}
export function downloadReport(report,filename){
 createReportPDF(report).save(filename.replace(/\.(html|txt|md)$/i,'')+'.pdf');
}
