// Prepared demonstration approved for implementation by the researcher.
// Illustrative proposals, not validated findings or live model output.
export function isEnergyDemo(value) {
 const text=value.toLowerCase().replace(/[^a-z0-9]/g,'');
 return text==='energyconsumptionperrevenue'||text==='energyconsumptionrevenue';
}
const rows=[
 ['control','Operational, with strategic influences','Operational teams influence energy use. Pricing, sales mix, investment and organisational boundaries also affect the result.'],
 ['impact','Direct on energy use; indirect on the company-wide ratio','Energy-saving actions can influence the numerator directly. Their effect on the ratio depends on revenue and other changes. Timing varies with the action.'],
 ['time','Backward-looking','Uses recorded energy consumption and revenue from a completed reporting period.'],
 ['complexity','Low structural complexity; distal and interaction complexity require examination','The calculation is simple, but the relationship between energy use and revenue may depend on prices, production volumes and product mix.'],
 ['transparency','Potentially standardized; methodological robustness conditional','A familiar ratio is not sufficient. Energy coverage, revenue definition, units and organisational boundaries must be explicit.'],
 ['stakeholder','Dual orientation','Combines resource consumption with financial activity, although it does not directly measure environmental damage or profitability.'],
 ['accuracy','Conditional on the intended use','Suitable for measuring energy per revenue. Insufficient by itself to establish physical energy efficiency or absolute environmental improvement.'],
 ['reliability','Conditional on consistent methods and boundaries','Comparisons require consistent energy coverage, revenue treatment and reporting periods. Price changes can affect interpretation even when measurement is consistent.'],
 ['cost','Potentially low incremental cost','Low if comparable energy and revenue data already exist. Allocation, missing meters or reconciliation may increase the effort required.']
];
export const energyDemo={kind:'demo',generationId:'prepared-energy-revenue-v1',evidenceVersion:'illustrative-demo-v1',sources:{},assessment:{
 name:'Energy consumption per revenue',definition:'An indicator of the energy consumed relative to the revenue generated during the same reporting period.',formula:'Total energy consumption (MWh) ÷ Revenue (€ million)',sustainabilityComponent:'Total energy consumption (MWh)',financialComponent:'Revenue (€ million)',eligibility:'integrated',
 summary:'A lower value means less energy consumed per unit of revenue. It does not necessarily mean that total energy consumption fell or operational efficiency improved. Higher selling prices, changes in product mix, or outsourcing could also reduce the ratio.',
 example:'12,000 MWh ÷ €60 million = 200 MWh per € million of revenue.',decision:'Decide whether this indicator provides a useful basis for monitoring energy performance and identifying where further investigation or investment is needed.',clarifyingQuestions:[],
 attributes:Object.fromEntries(rows.map(([id,classification,reasoning])=>[id,{classification,reasoning,assumptions:['Energy consumption and revenue refer to the same reporting period and organisational boundary.'],missingEvidence:['Confirm the method, data coverage and intended use before accepting this proposed assessment.'],evidenceIds:[]} ])),
 conflicts:[
 {title:'The ratio improved, but did energy performance improve?',attributeIds:['complexity','transparency','accuracy'],cfo:'Revenue increased following a price adjustment. Part of the improvement could come from the denominator.',sustainability:'Before describing this as progress, I need to know whether total energy consumption also decreased.',operations:'We used less energy per unit produced, but the revenue ratio does not show which operational changes contributed.',reasoning:'Changes in revenue can make the ratio improve even when energy use does not fall.',solution:'Present the ratio alongside total energy consumption and energy per unit of output, where a meaningful output measure exists. Explain the contribution of energy use, selling prices, production volume and product mix before making a performance claim.',agenda:'Agree what counts as improvement and which supporting measures are needed.',expectedOutcome:'An agreed interpretation rule and a set of supporting measures.',lead:'CFO and sustainability manager',evidenceIds:[]},
 {title:'Who should be accountable for the result?',attributeIds:['control','impact'],cfo:'The company needs an overall indicator, but revenue depends on several functions.',sustainability:'Responsibility for energy performance needs to be shared with the teams that can influence it.',operations:'We can influence equipment settings and energy use. We cannot control selling prices or company revenue.',reasoning:'Accountability should reflect the drivers each team can influence.',solution:'Use the company-wide ratio for an overall review. Where teams are evaluated, pair it with measures of energy use that reflect their responsibilities and controllable activities.',agenda:'Assign responsibility for the indicator’s drivers and agree suitable measures for each team.',expectedOutcome:'Named owners, agreed responsibilities and measures matched to each team’s influence.',lead:'CFO and Business',evidenceIds:[]},
 {title:'Are the figures comparable enough to support a decision?',attributeIds:['transparency','accuracy','reliability','cost'],cfo:'Revenue includes the newly acquired business. Does the energy figure cover it too?',sustainability:'Some sites use estimated energy data. We should make that limitation visible.',operations:'We have monthly meter readings, but allocating consumption across product lines would require more work.',reasoning:'Mismatched boundaries and undocumented estimates can undermine interpretation.',solution:'Align energy and revenue boundaries, document estimates and distinguish measured from estimated consumption. Use additional allocation only where the decision justifies the effort.',agenda:'Confirm reporting boundaries, data limitations and the minimum additional evidence required.',expectedOutcome:'A documented calculation method, an evidence checklist and owners for unresolved data gaps.',lead:'CFO, sustainability manager and Business',evidenceIds:[]}
 ]}};
