export const reviewRoles = ['CFO', 'Sustainability manager', 'Operations department'];
export const eps = {
  name: 'Carbon-adjusted earnings per share',
  formula: '[Net income − (Total GHG emissions × Carbon price per tonne CO₂e)] ÷ Total number of common shares',
  definition: 'Profit per share after subtracting an estimated monetary cost for the company’s greenhouse gas emissions.',
  sustainability: 'Total GHG emissions × carbon price per tonne CO₂e',
  financial: 'Net income and number of common shares',
};
// Baselines are supplied by the researcher. Role interpretations are proposed
// applications, not interview findings or independently validated assessments.
export const epsProfile = [
  { id:'control', value:'Strategic', assumption:'Long-term managerial decisions influence earnings and emissions. Input/output orientation remains unspecified.', roles:[['Strategic','Influence investment and organisational priorities.'],['Strategic contribution','Influence the emissions pathway; authority over earnings must be established.'],['Operational contribution to a strategic metric','Influence local emissions drivers; enterprise earnings and share count may sit outside this role.']] },
  { id:'impact', value:'Indirect · delayed', assumption:'Actions work through intervening processes and take time to affect measured results.', roles:[['Indirect · delayed','Capital allocation affects subsequent earnings and emissions.'],['Indirect · delayed','Programmes depend on implementation across functions.'],['Indirect · delayed at company level','Local changes may appear sooner; their effect on company EPS requires tracing.']] },
  { id:'time', value:'Past-oriented · proposed', assumption:'Proposed classification, pending researcher confirmation. Earnings and emissions describe the same completed reporting period.', roles:[['Past-oriented · proposed','A historical result can inform future investment choices.'],['Past-oriented · proposed','Annual emissions describe realised performance.'],['Past-oriented · proposed','Annual aggregation may obscure the timing of operational changes.']] },
  { id:'complexity', value:'Low across all three dimensions', assumption:'Researcher proposes low structural, distal and interaction complexity. Simple arithmetic does not by itself establish a simple relationship between carbon value and earnings.', roles:[['Low · provisional','Structural, distal and interaction levels follow the baseline; the valuation logic still needs scrutiny.'],['Low · provisional','Check whether the carbon price represents the intended environmental construct.'],['Low · provisional','Assumes emissions data can be combined without additional allocation modelling.']] },
  { id:'transparency', value:'Customized · robust, conditionally', assumption:'Researcher assumes the carbon price is disclosed. Proposed additional checks cover price rationale, emissions boundaries, data sources and a reproducible calculation.', roles:[['Customized · conditional robustness','Need a clear reconciliation from net income to adjusted EPS.'],['Customized · conditional robustness','Need the emissions boundary and carbon-price rationale.'],['Customized · conditional robustness','Need traceable activity data and allocation rules.']] },
  { id:'stakeholder', value:'Dual orientation', assumption:'The metric is intended to connect financial performance and sustainability. Role titles do not determine individual priorities.', roles:[['Dual orientation','Consider earnings and the strategic implications of carbon.'],['Dual orientation','Check that the combined number retains environmental meaning.'],['Dual orientation','Connect environmental actions with financial consequences.']] },
  { id:'accuracy', value:'High · provisional', assumption:'Researcher proposes high accuracy under stable measurement and construct over time. Precision and construct specificity still require evidence; consistency alone is insufficient.', roles:[['High · provisional','Confirm what kind of earnings adjustment the carbon cost represents.'],['High · provisional','Confirm emissions precision and the fit between price and intended construct.'],['High · provisional','Confirm the granularity and precision of source measurements.']] },
  { id:'reliability', value:'High · conditional', assumption:'Underlying conditions are comparable and temporal and methodological consistency hold across the last two reporting periods. Explain or reconcile boundary and method changes.', roles:[['High · conditional','Distinguish performance changes from changes in price, method or share count.'],['High · conditional','Compare emissions coverage and methods across both periods.'],['High · conditional','Check consistent activity data and emission-factor methods.']] },
  { id:'cost', value:'Low · incremental cost', assumption:'Financial and emissions data are already collected separately. Little extra monetary expenditure or staff effort is required to combine and maintain them.', roles:[['Low · conditional','Existing reporting systems supply the inputs.'],['Low · conditional','Assumes no additional footprint estimation or assurance is needed.'],['Low · conditional','Assumes no new metering, reconciliation or allocation work.']] },
];
export const epsIssues = [
  {id:'meaning',title:'What does the carbon cost represent?',kind:'Clarification needed',attrs:['complexity','transparency','accuracy'],positions:['Is this expected financial exposure, a shadow price or an environmental valuation?','Does the price represent the environmental consequence we intend to measure?','Which emissions quantities and operating boundaries enter the calculation?'],why:'Agreement on the formula does not establish agreement on what the deducted cost means.',question:'Agree what the carbon price represents and document its source and rationale.',output:'A shared interpretation of the adjustment, documented boundaries and a price sensitivity check.'},
  {id:'control',title:'Who can influence the result?',kind:'Responsibility to assign',attrs:['control','impact'],positions:['Which strategic decisions can change company earnings and emissions?','Which emissions drivers can this function influence through other teams?','Which local drivers can my team influence, and which company-level factors are outside its control?'],why:'A strategic company metric may be used to evaluate managers who control only some of its drivers.',question:'Agree which drivers each role controls and whether company-level EPS is appropriate for operational accountability.',output:'Named responsibilities, suitable local measures and a treatment of external influences.'},
  {id:'evidence',title:'What makes the assessment defensible?',kind:'Evidence needed',attrs:['transparency','accuracy','reliability','cost'],positions:['Can we reconcile the adjustment and compare the reporting periods?','Are emissions coverage, methods and price assumptions sufficiently documented?','Are the underlying data already available at the required precision, without extra collection?'],why:'High accuracy and reliability, robust methods and low cost are conditional assessments, not established properties of the formula.',question:'Check the evidence for precision, comparability and incremental cost before accepting the proposed profile.',output:'An evidence checklist, named owners and any revised attribute assessments.'},
];
export const integrationChecks = [
 ['Decision relevance','What decision would connecting these metrics improve?'],
 ['Underlying relationship','What evidence connects the sustainability variable to the financial outcome?'],
 ['Compatible boundaries','Do both metrics cover the same activities, organisational level and reporting period?'],
 ['Integration method','Would a ratio, monetary adjustment or another design preserve the information needed?'],
 ['Interpretation','Could a combined number conceal deterioration in either component?'],
];
export function worksheetIssues(metric, paired) {
  return [
    {id:'meaning', title:paired?'Is integration meaningful for this decision?':'What should an improvement mean?',kind:'Clarification needed',attrs:['stakeholder','accuracy','complexity'],positions:[`What would these inputs change in the decision “${metric.decision}”?`,`What environmental outcome should “${metric.sustainability}” represent?`,`What operational action could influence “${metric.name}”?`],why:paired?'No integration method is established from metric names alone. A supported connection must be demonstrated.':'The submitted formula needs a shared interpretation before classifications can be justified.',question:paired?'Establish whether the two metrics have a defensible relationship for the intended decision.':'Agree what improvement in the submitted metric should represent.',output:paired?'Choose whether to develop an integrated candidate, obtain more evidence, or retain linked separate measures.':'A shared definition of improvement and the intended decision consequence.'},
    {id:'control',title:'Who can act on these drivers?',kind:'Responsibility to assign',attrs:['control','impact','time'],positions:['Who owns the decision and resource allocation?','Who owns the sustainability outcome and its measurement?','Which drivers can the responsible team influence, and over what period?'],why:`Decision context supplied by the user: ${metric.context}`,question:'Confirm responsibility, controllable drivers and an appropriate evaluation horizon.',output:'Agreed responsibilities and a horizon that reflects the action-to-outcome pathway.'},
    {id:'evidence',title:'What evidence is still needed?',kind:'Evidence needed',attrs:['transparency','reliability','accuracy','cost'],positions:[`How is “${metric.financial}” calculated and reconciled?`,`What are the sources and boundaries for “${metric.sustainability}”?`,'Can the source data be reproduced and maintained at an acceptable cost?'],why:'These are framework-based prompts. This worksheet does not infer attribute levels or predict role opinions.',question:'Document sources, units, periods, boundaries and methodological choices before assessing the nine attributes.',output:'An evidence request and an assessment plan; leave unsupported classifications unassessed.'},
  ];
}
