export const roles = ["CFO", "Sustainability manager", "Operations manager"];
export const groups = ["Performance-related", "Sustainability-related", "Signaling-related"];
const level = ["Not assessed", "Low", "Medium", "High"];
export const attributes = [
  { id: "control", name: "Controllability", group: 0, definition: "The scope of managerial oversight and the type of control exercised: what a manager can influence and at what level that influence operates.", dimensions: [{ name: "Level of influence", options: ["Not assessed", "Strategic", "Operational", "Both"] }, { name: "Measurement orientation", options: ["Not assessed", "Input-oriented", "Output-oriented", "Both"] }], detail: "Strategic indicators reflect long-term managerial decisions; operational indicators capture day-to-day actions. Input indicators measure resources invested; output indicators reflect results achieved.", questions: ["Which drivers can the responsible manager change?", "Could external prices or another team’s decisions outweigh those actions?"], reference: "Bol & Smith (2011); Giraud et al. (2008)" },
  { id: "impact", name: "Managerial impact", group: 0, definition: "The extent and timing of managerial influence on the measured results.", dimensions: [{ name: "Influence pathway", options: ["Not assessed", "Direct", "Indirect", "Both"] }, { name: "Timing of effect", options: ["Not assessed", "Immediate", "Delayed", "Both"] }], detail: "Direct impacts operate without intermediaries; indirect impacts involve mediating processes. Immediate impacts are observable in real time; delayed impacts emerge after a lag.", questions: ["What has to happen between the action and the measured outcome?", "How long should the team wait before judging whether an action worked?"], reference: "Coles & Li (2020); Libby et al. (2004)" },
  { id: "time", name: "Time orientation", group: 0, definition: "The temporal focus of the indicator: realised performance, anticipated outcomes, or a combination.", dimensions: [{ name: "Temporal focus", options: ["Not assessed", "Past-oriented", "Future-oriented", "Dual-temporal"] }], detail: "Past-oriented indicators use historical performance. Future-oriented indicators incorporate forecasts or scenarios. A dual-temporal assessment should identify both its historical and prospective elements.", questions: ["Can a reader distinguish observed results from forecasts?", "Does the evaluation period capture when the benefit is expected to arrive?"], reference: "Chakhovich (2019); Franco-Santos et al. (2012)" },
  { id: "complexity", name: "Indicator complexity", group: 1, definition: "The analytical difficulty of connecting sustainability and financial information in a single indicator.", dimensions: [{ name: "Structural complexity", options: level }, { name: "Distal complexity", options: level }, { name: "Interaction complexity", options: level }], detail: "Structural complexity concerns the modelling needed to connect variables. Distal complexity concerns the distance between the sustainability variable and financial outcome. Interaction complexity concerns the number and behaviour of interacting variables. Intensity selections here are provisional descriptors, not a validated scoring rubric.", questions: ["Which assumption is doing the most work in connecting sustainability and finance?", "Could a plausible change in an input reverse the decision?"], reference: "Carmine & De Marchi (2023); Hahn et al. (2018)" },
  { id: "transparency", name: "Transparency", group: 1, definition: "How clearly internal and external stakeholders can understand the indicator’s construction, assumptions and underlying logic.", dimensions: [{ name: "Design basis", options: ["Not assessed", "Recognised framework", "Customised", "Combination"] }, { name: "Standardization clarity", options: level }, { name: "Methodological robustness", options: level }], detail: "Standardization clarity covers the use and documentation of recognised frameworks or customised approaches. Methodological robustness covers detail about sources, assumptions, estimation and boundaries sufficient for replication and verification. A customised metric can still be transparent.", questions: ["Could someone outside the team reproduce the result?", "Which assumptions and boundaries need to be documented before the metric is used?"], reference: "Friske et al. (2023)" },
  { id: "stakeholder", name: "Stakeholder orientation", group: 1, definition: "The intended audience and the evaluative logic that shapes how a metric is interpreted.", dimensions: [{ name: "Intended orientation", options: ["Not assessed", "Finance-oriented", "Sustainability-oriented", "Dual-interest"] }], detail: "Financial orientations emphasise profitability, risk and resilience. Sustainability orientations emphasise moral and ecological impacts. Dual-interest orientations seek to integrate financial and environmental performance. A job title does not establish an individual’s orientation.", questions: ["Whose definition of good performance does this metric express?", "What should it communicate when financial and environmental outcomes move in opposite directions?"], reference: "Sinnewe et al. (2021); Stubbs & Higgins (2018)" },
  { id: "accuracy", name: "Accuracy", group: 2, definition: "The precision and specificity with which an indicator captures its intended phenomenon.", dimensions: [{ name: "Measurement precision", options: level }, { name: "Construct specificity", options: level }], detail: "Measurement precision concerns numerical exactness and granularity. Construct specificity concerns the clarity and appropriateness of the concept measured. A formula alone cannot establish the quality of underlying data.", questions: ["Does the metric measure the intended phenomenon or a proxy for it?", "Are the reported numbers more precise than the underlying evidence supports?"], reference: "Bergh et al. (2014); Luo & Wu (2022)" },
  { id: "reliability", name: "Reliability", group: 2, definition: "The stability of an indicator across time and methodological choices.", dimensions: [{ name: "Temporal consistency", options: level }, { name: "Methodological stability", options: level }], detail: "Temporal consistency means comparable results when underlying conditions remain stable. Methodological stability means changes are transparent, justified and systematically applied. Historical and methodological evidence is needed to assess both.", questions: ["Could a method change look like a performance improvement?", "Would a different data provider or estimation method materially change the result?"], reference: "Al-Shaer (2020); Crepaz & Chari (2018)" },
  { id: "cost", name: "Signal cost", group: 2, definition: "The resources required to produce and maintain an integrated KPI.", dimensions: [{ name: "Monetary cost", options: level }, { name: "Resource-based cost", options: level }], detail: "Monetary costs include collection, verification, systems and reporting infrastructure. Resource-based costs include labour, expertise, analytical effort and computation. Higher expenditure does not automatically establish credibility.", questions: ["What would maintaining this metric require each reporting cycle?", "Which resources strengthen verification rather than simply adding expense?"], reference: "Connelly et al. (2011); Desjardine et al. (2021)" },
];
export const statuses = ["Clarification needed", "Evidence needed", "Trade-off to decide", "Responsibility to assign", "Agreement under conditions"];
export const examples = [
  { id: "revenue", name: "Revenue per tonne of CO₂e", category: "Carbon efficiency", formula: "Revenue ÷ tonnes of CO₂e", decision: "Assess whether commercial growth is becoming less emissions-intensive.", context: "A company is comparing annual revenue with its emissions footprint.", horizon: "Annual review", family: "Ratio or intensity", meaning: "Higher revenue for each tonne emitted", profile: { control: ["Both", "Output-oriented"], impact: ["Both", "Both"], time: ["Past-oriented"], stakeholder: ["Dual-interest"] } },
  { id: "npv", name: "Carbon-adjusted project NPV", category: "Investment decisions", formula: "Project NPV − discounted carbon cost", decision: "Compare conventional and lower-emission investment options.", context: "An internal carbon price is proposed for project appraisal. Carbon costs already included in cash flows must not be counted twice.", horizon: "Project lifetime", family: "Monetised or adjusted", meaning: "A stronger investment case after the carbon adjustment", profile: { control: ["Strategic", "Output-oriented"], impact: ["Indirect", "Delayed"], time: ["Future-oriented"], stakeholder: ["Dual-interest"] } },
  { id: "energy", name: "Verified energy savings in euros", category: "Resource efficiency", formula: "Verified energy avoided × agreed energy price", decision: "Assess the contribution of an energy-efficiency project.", context: "The proposed baseline is adjusted for output. A shared energy price separates physical savings from price movements.", horizon: "Annual review", family: "Monetised or adjusted", meaning: "Verified physical energy reductions expressed in financial terms", profile: { control: ["Operational", "Output-oriented"], impact: ["Direct", "Delayed"], time: ["Past-oriented"], stakeholder: ["Dual-interest"] } },
];
export const blankMetric = { id: "custom", name: "", formula: "", decision: "", context: "", horizon: "Not specified", family: "Not specified", meaning: "", profile: {} };
function issue(id, title, type, attrs, positions, consequence, question, output, owner, why) {
  return { id, title, type, attrs, positions, consequence, question, output, owner, why };
}
export function buildIssues(metric) {
  const custom = metric.id === "custom";
  const list = [
    issue("meaning", "What counts as an improvement?", "Clarification needed", ["stakeholder", "accuracy"],
      custom ? ["Which change in financial performance would justify action?", "Does improvement in this metric imply improvement in the underlying impact?", "Which physical operating change should the metric represent?"] : metric.id === "revenue" ? ["Higher revenue per tonne signals stronger commercial efficiency.", "Check absolute emissions before interpreting the ratio as impact progress.", "Separate process improvements from price and product-mix effects."] : metric.id === "npv" ? ["Is the adjustment a forecast cash expense or a shadow-price assumption?", "Does the adjustment represent the environmental consequence we intend to capture?", "Which feasible project change would improve the adjusted result?"] : ["Distinguish gross savings from net financial value.", "Confirm physical energy reductions and their emissions implications.", "Separate real efficiency from output or operating-condition changes."],
      "People may agree on the number but act on different meanings.", `Agree what an improvement in “${metric.name}” should mean for the intended decision.`, "A shared definition of success and any accompanying measure.", "All three roles", "Every review starts with the relationship between the metric’s meaning and its intended decision."),
    issue("evidence", "What evidence is sufficient?", "Evidence needed", ["accuracy", "reliability", "transparency"],
      [custom ? "What would make the financial inputs defensible?" : "Need defensible financial inputs and a traceable calculation.", custom ? "How will the sustainability data and boundaries be verified?" : "Need credible physical data and explicit sustainability boundaries.", custom ? "What measurement or pilot would establish operational feasibility?" : "Need operational measurements that can be reproduced."],
      "A persuasive result may still depend on unverified inputs.", "Agree which inputs, boundaries and verification steps are needed before relying on the metric.", "An evidence checklist, with missing data and verification tasks.", "Finance, sustainability and operations", "No evidence files are attached to this prototype; data quality and reliability remain unestablished."),
    issue("horizon", "Which time horizon governs?", "Trade-off to decide", ["time", "impact"],
      [custom ? "Does the evaluation period capture the relevant financial effects?" : "Evaluate performance within an agreed financial horizon.", custom ? "Will sustainability effects appear within that same period?" : "Include sustainability effects that may emerge later.", custom ? "When could the team deliver and measure the outcome?" : "Allow for installation, operating cycles and a measurement lag."],
      "The evaluation may end before the expected benefit is visible.", `Agree the evaluation horizon${metric.horizon === "Not specified" ? "" : `, starting from “${metric.horizon}”`}, and how later outcomes will be treated.`, "An agreed horizon and treatment of delayed effects.", "All three roles", `The metric uses the horizon “${metric.horizon}”. This prompts a timing discussion, not a claim that the roles disagree.`),
    issue("ownership", "Who can act, and who is accountable?", "Responsibility to assign", ["control", "cost"],
      [custom ? "Who funds the action and receives its financial benefit?" : "Clarify the funding owner and where financial benefits accrue.", custom ? "Who owns the sustainability target and its verification?" : "Clarify ownership of the sustainability target and evidence.", custom ? "Can the accountable team influence the main drivers?" : "Match operating accountability to drivers the team can influence."],
      "A coherent metric can fail when cost, benefit and control sit in different teams.", "Assign responsibility for controllable drivers, measurement and follow-up; identify external influences.", "Named responsibilities and a treatment of factors outside managerial control.", "All three roles", "A role title does not identify actual decision rights or budget ownership."),
  ];
  if (metric.family === "Ratio or intensity") list.push(issue("ratio", "Can the ratio improve without progress?", "Trade-off to decide", ["accuracy", "stakeholder", "complexity"],
    ["Would price or denominator changes improve the ratio?", "Could absolute environmental impacts worsen while the ratio improves?", "Which physical change can be separated from composition effects?"],
    "The combined number could hide a deterioration that matters to the decision.", "Decide whether an absolute outcome measure or guardrail should accompany the ratio.", "An agreed accompanying measure or explicit interpretation constraint.", "Finance and sustainability", "Triggered by the selected ratio/intensity family. These are questions to investigate."));
  if (metric.family === "Monetised or adjusted") list.push(issue("valuation", "Which valuation assumptions are acceptable?", "Clarification needed", ["complexity", "transparency", "accuracy"],
    ["How do price, discounting and double counting affect the result?", "Does the monetary conversion represent the intended sustainability phenomenon?", "Are the physical quantities achievable and measurable?"],
    "A modelling choice could reverse the apparent decision or overstate value.", "Document the conversion assumptions and check whether plausible alternatives change the decision.", "A transparent valuation method and an agreed sensitivity check.", "Finance, with sustainability and operations", "Triggered by the selected monetised/adjusted family. No numerical sensitivity is calculated."));
  if (metric.id === "energy") list.push(issue("baseline", "Is the baseline agreed?", "Agreement under conditions", ["reliability", "accuracy"],
    ["Use an agreed energy price to separate savings from price movements.", "Verify the physical energy reduction and accompanying emissions measure.", "Normalise the baseline for output and operating conditions."],
    "The shared direction depends on accepting and checking the same baseline.", "Confirm who verifies the output-adjusted baseline, agreed price and ongoing costs.", "An accepted baseline with verification responsibilities.", "Operations, with finance and sustainability", "The energy example explicitly proposes an output-adjusted baseline; agreement is illustrative and conditional."));
  return list.map(item => ({ ...item, evidence: custom ? "Rule-based prompt" : item.id === "ratio" || item.id === "valuation" ? "Rule-based prompt" : "Illustrative scenario" }));
}
export function makeReview(metric) {
  return { metric: { ...metric }, issues: buildIssues(metric), entries: {}, ratings: Object.fromEntries(attributes.map(a => [a.id, a.dimensions.map((d, i) => metric.profile[a.id]?.[i] || d.options[0])])), notes: {}, editedRatings: {} };
}
export function activeIssues(review) {
  return review.issues.filter(i => !review.entries[i.id]?.resolved);
}
export function questionSet(review) {
  const m = review.metric;
  return [
    { id: "meaning", attribute: "Stakeholder orientation", question: `What must be true for “${m.meaning || "an improvement in this metric"}” to support the intended decision?` },
    { id: m.family === "Ratio or intensity" ? "ratio" : m.family === "Monetised or adjusted" ? "valuation" : "evidence", attribute: m.family === "Not specified" ? "Transparency" : "Indicator complexity", question: m.family === "Ratio or intensity" ? "Could this ratio improve while the absolute sustainability outcome worsens?" : m.family === "Monetised or adjusted" ? "Could a plausible change in the valuation assumptions reverse the decision?" : "What data sources, boundaries and assumptions would another person need to reconstruct this metric?" },
    { id: "horizon", attribute: "Time orientation", question: `Would the expected benefit become observable within ${m.horizon === "Not specified" ? "the evaluation period" : m.horizon.toLowerCase()}?` },
  ];
}
export function exportAgenda(review) {
  const open = activeIssues(review);
  return ["METRIC LAB — MEETING AGENDA", review.metric.name, "", `Formula: ${review.metric.formula}`, `Intended decision: ${review.metric.decision}`, `Context: ${review.metric.context}`, `Horizon: ${review.metric.horizon}`, "", "Exploratory prototype. Interview evidence and predictive AI are not connected.", "Role positions are illustrative or entered by the user; questions are generated by explicit rules.", "", ...open.flatMap((i, n) => [`${n + 1}. ${i.question}`, `Issue: ${i.title} (${review.entries[i.id]?.type || i.type})`, `Expected output: ${i.output}`, `Suggested participants: ${i.owner}`, `Basis: ${i.evidence}`, ...roles.map((role, ix) => `${role} (${review.entries[i.id]?.positions?.[ix] !== undefined ? "user-entered position" : i.evidence}): ${review.entries[i.id]?.positions?.[ix] ?? i.positions[ix]}`), `Notes: ${review.entries[i.id]?.note || "None entered"}`, ""]), ...review.issues.filter(i => review.entries[i.id]?.resolved).flatMap(i => [`RESOLVED BY USER: ${i.title}`, `Resolution: ${review.entries[i.id].note}`, ""]), "ATTRIBUTE PROFILE", ...attributes.flatMap(a => [`${a.name} (${review.editedRatings[a.id] ? "user assessment" : review.metric.id === "custom" ? "not assessed" : "illustrative working profile"}): ${a.dimensions.map((d, ix) => `${d.name} = ${review.ratings[a.id][ix]}`).join("; ")}`, `Rationale: ${review.notes[a.id] || "Not recorded"}`])].join("\n");
}
