'use client';
import {useState,useRef,useEffect} from 'react';
import {attributes} from '../lib/metric-data';
import {eps,epsProfile,epsIssues} from '../lib/eps-case';
const roles=[['ceo','CEO'],['sustainability','Sustainability manager'],['operations','Operational manager']];
export default function AIReview(){
 const [mode,setMode]=useState('existing'),[metric,setMetric]=useState(''),[context,setContext]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[tab,setTab]=useState(0),[resolved,setResolved]=useState({});
 const [availability,setAvailability]=useState('checking');
 const controller=useRef(null),outputRef=useRef(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/assess',{signal:c.signal,cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setAvailability(d.configured?'configured':'unavailable')).catch(e=>{if(e.name!=='AbortError')setAvailability('unknown')});return()=>c.abort()},[]);
 function openExample(){
  if(busy)return;
  setError('');setResolved({});setTab(0);
  setResult({kind:'example',generationId:'prepared-eps-v1',evidenceVersion:'researcher-baseline-v1',sources:{},assessment:{...eps,sustainabilityComponent:eps.sustainability,financialComponent:eps.financial,eligibility:'integrated',summary:'A researcher-supplied baseline with conditional assumptions and illustrative managerial interpretations.',clarifyingQuestions:['Does the carbon price represent an expected expense, an internal shadow price or an estimated environmental cost?'],attributes:Object.fromEntries(epsProfile.map(p=>[p.id,{classification:p.value,reasoning:p.assumption,assumptions:[p.assumption],missingEvidence:['Confirm that the stated assumptions apply to the company and reporting period.'],evidenceIds:[],...Object.fromEntries(roles.map(([key],i)=>[key,{assessment:p.roles[i][0],reasoning:p.roles[i][1]}]))}])),conflicts:epsIssues.map(i=>({title:i.title,attributeIds:i.attrs,ceo:i.positions[0],sustainability:i.positions[1],operations:i.positions[2],reasoning:i.why,evidenceIds:[],agenda:i.question,expectedOutcome:i.output}))}});
  requestAnimationFrame(()=>outputRef.current?.focus());
 }

 async function assess(e){e.preventDefault();if(busy)return;setBusy(true);setError('');controller.current=new AbortController();try{const response=await fetch('/api/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,metric,context}),signal:controller.current.signal});const data=await response.json().catch(()=>{throw Error('The assessment service returned an unexpected response. Please retry. Your entries remain in the form.');});if(!response.ok){if(data.code==='AI_SETUP_REQUIRED')setAvailability('unavailable');throw Error(data.error||'Assessment unavailable.');}setAvailability('configured');setResult(data);setResolved({});setTab(0);requestAnimationFrame(()=>outputRef.current?.focus())}catch(e){setError(e.name==='AbortError'?'Assessment cancelled.':e.message)}finally{setBusy(false)}}
 function download(){const a=result.assessment;const text=['METRIC LAB ASSESSMENT',a.name,a.summary,result.kind==='example'?'Prepared researcher baseline; role interpretations are illustrative and assumptions remain conditional.':'Proposed AI assessment grounded in de-identified coding summaries. Not researcher-validated.',`Formula: ${a.formula}`,`Generation: ${result.generationId}`,`Evidence version: ${result.evidenceVersion}`,'',...attributes.flatMap(attr=>{const p=a.attributes[attr.id];return [attr.name,p.classification,p.reasoning,`Assumptions: ${p.assumptions.join('; ')}`,`Missing evidence: ${p.missingEvidence.join('; ')}`,...roles.map(([k,n])=>`${n}: ${p[k].assessment}. ${p[k].reasoning}`),`Evidence: ${p.evidenceIds.join(', ')}`,'']}),'MEETING AGENDA',...a.conflicts.flatMap((c,i)=>resolved[i]?.done?[`RESOLVED: ${c.title}`,resolved[i].note]:[c.agenda,c.expectedOutcome,`Source issue: ${c.title}`,resolved[i]?.note||'']),'EVIDENCE PARAPHRASES',...Object.entries(result.sources).map(([id,text])=>`${id}: ${text}`),'CLARIFYING QUESTIONS',...a.clarifyingQuestions].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='Metric-Lab-Assessment.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function citations(ids){return ids.length?<details className="simple-details"><summary>Supporting evidence ({ids.length})</summary>{ids.map(id=><p key={id}><strong>{id}</strong> · {result.sources[id]}</p>)}<p>Paraphrased coding themes. Their application here is an AI interpretation.</p></details>:<p className="ai-meta">{result.kind==='example'?'Prepared example; no interview theme cited.':'Framework-based inference; no interview theme cited.'}</p>}
 const a=result?.assessment;
 return <section className="workbench ai-workbench" aria-label="Assess your metric"><div className="entry-heading"><h3>Assess your metric.</h3><p>Bring an integrated KPI or separate measures. The research guides the assessment; your context gives it meaning.</p></div><div className="example-switch"><button type="button" className="text-button" disabled={busy} onClick={openExample}>Try an example · Carbon-adjusted EPS</button><span>Prepared assessment · no AI connection needed</span></div><div className="evidence-banner" role="status" hidden={!!error}><p>{availability==='checking'?'Checking custom assessment availability…':availability==='configured'?'An AI connection is configured. Submit your metric to request a research-grounded assessment.':availability==='unknown'?'The connection check could not complete. You can still enter and submit your metric to try the assessment.':'The AI connection needs attention. You can enter your metric and retry after activation, or explore the prepared EPS example. Your entries stay here while this page remains open.'}</p></div><form onSubmit={assess} className="custom-form"><fieldset disabled={busy} style={{border:0,padding:0}}><label>What are you bringing?<select value={mode} onChange={e=>setMode(e.target.value)}><option value="existing">An integrated KPI</option><option value="paired">Separate financial and sustainability metrics</option></select></label><div className="custom-fields"><label>{mode==='existing'?'iKPI name and formula, if known':'Financial and sustainability metrics'}<textarea required maxLength={4000} rows={3} value={metric} onChange={e=>setMetric(e.target.value)} placeholder={mode==='existing'?'For example, carbon-adjusted total cost of ownership':'Describe both measures and their units.'}/></label><label>Decision and company context (optional)<textarea maxLength={3000} rows={3} value={context} onChange={e=>setContext(e.target.value)} placeholder="What decision should this support? Include reporting period and data availability if known."/></label></div><p className="ai-meta">Your submission is sent to an AI provider for assessment. Use descriptions without personal or confidential company information. The reference material contains paraphrased coding themes, not interview transcripts.</p><button className="button primary" disabled={busy} type="submit">{busy?'Assessing your metric…':'Assess my metric ↗'}</button></fieldset>{busy&&<button type="button" className="text-button" onClick={()=>controller.current?.abort()}>Cancel assessment</button>}</form>{busy&&<p className="workbench-notice" role="status">Examining the framework, assumptions and relevant evidence. This may take a minute.</p>}{error&&<p role="alert" className="workbench-notice">{error}</p>}
 {a&&<div ref={outputRef} tabIndex={-1}><div className="review-overview"><div><span className="research-tag">{result.kind==='example'?'Prepared example · conditional researcher baseline':'AI proposal · review before use'}</span><h3>{a.name}</h3><p>{a.definition}</p><p>{a.summary}</p><span className="ai-meta">{a.eligibility.replaceAll('_',' ')} · {result.generationId.slice(0,8)}</span></div></div><div className="component-pair"><div><span>Sustainability component</span><strong>{a.sustainabilityComponent}</strong></div><div><span>Financial component</span><strong>{a.financialComponent}</strong></div></div><p className="formula-band">{a.formula}</p>{a.clarifyingQuestions.length>0&&<div className="key-question" style={{margin:30}}><h4>What still needs clarifying</h4>{a.clarifyingQuestions.map((q,i)=><p key={i}>{q}</p>)}</div>}<nav className="review-steps" aria-label="Assessment views">{['Understand the metric','Nine-attribute assessment','Potential conflict map','Meeting agenda'].map((s,i)=><button key={s} aria-current={tab===i?'step':undefined} onClick={()=>setTab(i)}>{s}</button>)}</nav><div className="lab-panel">{tab===0&&<div className="key-question"><h4>What does this metric mean for your decision?</h4><p>{a.summary}</p><p>Examine the assumptions, compare the three managerial perspectives, then prepare a discussion agenda.</p><button type="button" className="button primary" onClick={()=>setTab(1)}>Explore the nine-attribute assessment →</button></div>}
 {tab===1&&<div className="ai-attributes">{attributes.map(attr=>{const p=a.attributes[attr.id];return <article className="friction-card" key={attr.id}><h4>{attr.name} · {p.classification}</h4><p>{p.reasoning}</p><div className="role-comparison">{roles.map(([k,n])=><div key={k}><strong>{n}</strong><p>{p[k].assessment}</p><p>{p[k].reasoning}</p></div>)}</div><details className="simple-details"><summary>Assumptions and missing evidence</summary><h5>Assumptions</h5>{p.assumptions.length?p.assumptions.map((s,i)=><p key={i}>{s}</p>):<p>None stated.</p>}<h5>Missing evidence</h5>{p.missingEvidence.length?p.missingEvidence.map((s,i)=><p key={i}>{s}</p>):<p>None identified by the model; this is not verification.</p>}</details>{citations(p.evidenceIds)}</article>})}</div>}
 {tab===2&&<div className="conflict-cards">{!a.conflicts.length&&<p>No specific conflict identified. This does not establish agreement.</p>}{a.conflicts.map((c,i)=><article className="friction-card" key={i}><h4>{c.title}</h4><p>{c.reasoning}</p><div className="dimension-tags">{c.attributeIds.map(id=><span key={id}>{attributes.find(x=>x.id===id)?.name}</span>)}</div><div className="role-comparison">{roles.map(([k,n])=><div key={k}><strong>{n}</strong><p>{c[k]}</p></div>)}</div>{citations(c.evidenceIds)}<label>Resolution note<textarea value={resolved[i]?.note||''} onChange={e=>setResolved(prev=>({...prev,[i]:{note:e.target.value,done:e.target.value.trim()?prev[i]?.done:false}}))}/></label><label className="resolve-check"><input type="checkbox" checked={!!resolved[i]?.done} disabled={!resolved[i]?.note?.trim()} onChange={e=>setResolved(prev=>({...prev,[i]:{...prev[i],done:e.target.checked}}))}/>Mark resolved</label></article>)}</div>}
 {tab===3&&<><div className="agenda-list">{a.conflicts.filter((c,i)=>!resolved[i]?.done).map((c,i)=><article className="agenda-item" key={i}><div><h4>{c.agenda}</h4><p>{c.expectedOutcome}</p><button className="text-button" onClick={()=>setTab(2)}>Source issue · {c.title}</button></div></article>)}{a.conflicts.every((c,i)=>resolved[i]?.done)&&<p>No open agenda items. Review the clarifying questions and any recorded resolutions.</p>}</div></>}
 <button type="button" className="button primary" onClick={download}>Download assessment & agenda ↓</button><p className="ai-meta">{result.kind==='example'?'This prepared example combines a researcher baseline with illustrative role perspectives and conflicts.':'Role perspectives and conflicts are AI inferences. Evidence references show the material used, not independent validation.'} Download before reloading to retain this result.</p></div></div>}</section>
}
