'use client';
import {useState,useRef} from 'react';
import {attributes} from '../lib/metric-data';
const roles=[['ceo','CEO'],['sustainability','Sustainability manager'],['operations','Operational manager']];
export default function AIReview(){
 const [mode,setMode]=useState('existing'),[metric,setMetric]=useState(''),[context,setContext]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[tab,setTab]=useState(0),[resolved,setResolved]=useState({});
 const controller=useRef(null),outputRef=useRef(null);
 async function assess(e){e.preventDefault();setBusy(true);setError('');setResult(null);setResolved({});controller.current=new AbortController();try{const response=await fetch('/api/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,metric,context}),signal:controller.current.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Assessment unavailable.');setResult(data);setTab(0);requestAnimationFrame(()=>outputRef.current?.focus())}catch(e){setError(e.name==='AbortError'?'Assessment cancelled.':e.message)}finally{setBusy(false)}}
 function download(){const a=result.assessment;const text=['METRIC LAB AI ASSESSMENT',a.name,a.summary,'Proposed AI assessment grounded in de-identified coding summaries. Not researcher-validated.',`Formula: ${a.formula}`,`Generation: ${result.generationId}`,`Evidence version: ${result.evidenceVersion}`,'',...attributes.flatMap(attr=>{const p=a.attributes[attr.id];return [attr.name,p.classification,p.reasoning,`Assumptions: ${p.assumptions.join('; ')}`,`Missing evidence: ${p.missingEvidence.join('; ')}`,...roles.map(([k,n])=>`${n}: ${p[k].assessment}. ${p[k].reasoning}`),`Evidence: ${p.evidenceIds.join(', ')}`,'']}),'MEETING AGENDA',...a.conflicts.flatMap((c,i)=>resolved[i]?.done?[`RESOLVED: ${c.title}`,resolved[i].note]:[c.agenda,c.expectedOutcome,`Source issue: ${c.title}`,resolved[i]?.note||'']),'EVIDENCE PARAPHRASES',...Object.entries(result.sources).map(([id,text])=>`${id}: ${text}`),'CLARIFYING QUESTIONS',...a.clarifyingQuestions].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='Metric-Lab-AI-Assessment.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function citations(ids){return ids.length?<details className="simple-details"><summary>Supporting evidence ({ids.length})</summary>{ids.map(id=><p key={id}><strong>{id}</strong> · {result.sources[id]}</p>)}<p>Paraphrased coding themes. Their application here is an AI interpretation.</p></details>:<p className="ai-meta">Framework-based inference; no interview theme cited.</p>}
 const a=result?.assessment;
 return <section className="workbench ai-workbench" aria-label="AI metric assessment"><div className="entry-heading"><span className="research-tag">Research-grounded AI · experimental</span><h3>Let the research examine your metric.</h3><p>Assess an iKPI using the nine-attribute framework and 99 de-identified coding insights.</p></div><form onSubmit={assess} className="custom-form"><fieldset disabled={busy} style={{border:0,padding:0}}><label>What are you bringing?<select value={mode} onChange={e=>setMode(e.target.value)}><option value="existing">An integrated KPI</option><option value="paired">Separate financial and sustainability metrics</option></select></label><div className="custom-fields"><label>{mode==='existing'?'iKPI name and formula, if known':'Financial and sustainability metrics'}<textarea required maxLength={4000} rows={3} value={metric} onChange={e=>setMetric(e.target.value)} placeholder={mode==='existing'?'For example, carbon-adjusted total cost of ownership':'Describe both measures and their units.'}/></label><label>Decision and company context (optional)<textarea maxLength={3000} rows={3} value={context} onChange={e=>setContext(e.target.value)} placeholder="What decision should this support? Include reporting period and data availability if known."/></label></div><p className="ai-meta">Your submission is sent to an AI provider for assessment. Use descriptions without personal or confidential company information. The reference material contains paraphrased coding themes, not interview transcripts.</p><button className="button primary" disabled={busy} type="submit">{busy?'Assessing your metric…':'Assess with research AI ↗'}</button></fieldset>{busy&&<button type="button" className="text-button" onClick={()=>controller.current?.abort()}>Cancel assessment</button>}</form>{busy&&<p className="workbench-notice" role="status">Examining the framework, assumptions and relevant evidence. This may take a minute.</p>}{error&&<p role="alert" className="workbench-notice">{error}</p>}
 {a&&<div ref={outputRef} tabIndex={-1}><div className="review-overview"><div><span className="research-tag">AI proposal · review before use</span><h3>{a.name}</h3><p>{a.definition}</p><p>{a.summary}</p><span className="ai-meta">{a.eligibility.replaceAll('_',' ')} · {result.generationId.slice(0,8)}</span></div></div><div className="component-pair"><div><span>Sustainability component</span><strong>{a.sustainabilityComponent}</strong></div><div><span>Financial component</span><strong>{a.financialComponent}</strong></div></div><p className="formula-band">{a.formula}</p>{a.clarifyingQuestions.length>0&&<div className="key-question" style={{margin:30}}><h4>What still needs clarifying</h4>{a.clarifyingQuestions.map((q,i)=><p key={i}>{q}</p>)}</div>}<nav className="review-steps" aria-label="AI assessment views">{['Nine-attribute assessment','Potential conflict map','Meeting agenda'].map((s,i)=><button key={s} aria-current={tab===i?'step':undefined} onClick={()=>setTab(i)}>{s}</button>)}</nav><div className="lab-panel">
 {tab===0&&<div className="ai-attributes">{attributes.map(attr=>{const p=a.attributes[attr.id];return <article className="friction-card" key={attr.id}><h4>{attr.name} · {p.classification}</h4><p>{p.reasoning}</p><div className="role-comparison">{roles.map(([k,n])=><div key={k}><strong>{n}</strong><p>{p[k].assessment}</p><p>{p[k].reasoning}</p></div>)}</div><details className="simple-details"><summary>Assumptions and missing evidence</summary><h5>Assumptions</h5>{p.assumptions.length?p.assumptions.map((s,i)=><p key={i}>{s}</p>):<p>None stated.</p>}<h5>Missing evidence</h5>{p.missingEvidence.length?p.missingEvidence.map((s,i)=><p key={i}>{s}</p>):<p>None identified by the model; this is not verification.</p>}</details>{citations(p.evidenceIds)}</article>})}</div>}
 {tab===1&&<div className="conflict-cards">{!a.conflicts.length&&<p>No specific conflict identified. This does not establish agreement.</p>}{a.conflicts.map((c,i)=><article className="friction-card" key={i}><h4>{c.title}</h4><p>{c.reasoning}</p><div className="dimension-tags">{c.attributeIds.map(id=><span key={id}>{attributes.find(x=>x.id===id)?.name}</span>)}</div><div className="role-comparison">{roles.map(([k,n])=><div key={k}><strong>{n}</strong><p>{c[k]}</p></div>)}</div>{citations(c.evidenceIds)}<label>Resolution note<textarea value={resolved[i]?.note||''} onChange={e=>setResolved(prev=>({...prev,[i]:{note:e.target.value,done:e.target.value.trim()?prev[i]?.done:false}}))}/></label><label className="resolve-check"><input type="checkbox" checked={!!resolved[i]?.done} disabled={!resolved[i]?.note?.trim()} onChange={e=>setResolved(prev=>({...prev,[i]:{...prev[i],done:e.target.checked}}))}/>Mark resolved</label></article>)}</div>}
 {tab===2&&<><div className="agenda-list">{a.conflicts.filter((c,i)=>!resolved[i]?.done).map((c,i)=><article className="agenda-item" key={i}><div><h4>{c.agenda}</h4><p>{c.expectedOutcome}</p><button className="text-button" onClick={()=>setTab(1)}>Source issue · {c.title}</button></div></article>)}{a.conflicts.every((c,i)=>resolved[i]?.done)&&<p>No open agenda items. Review the clarifying questions and any recorded resolutions.</p>}</div></>}
 <button type="button" className="button primary" onClick={download}>Download AI assessment & agenda ↓</button><p className="ai-meta">Role perspectives and conflicts are AI inferences. Evidence references show the material used, not independent validation. Download before reloading to retain this result.</p></div></div>}</section>
}
