'use client';
import {attributes} from '../lib/metric-data';
const roles=[['cfo','CFO'],['sustainability','Sustainability manager'],['operations','Business']];
export default function EnergyReview({result,resolved,setResolved,onDownload}){
 const a=result.assessment;
 return <div className="prepared-review energy-review">
  <div className="prepared-intro"><span className="research-tag">Example assessment</span><h3>{a.name}</h3><p>{a.definition}</p><div className="component-pair"><div><span>Sustainability component</span><strong>{a.sustainabilityComponent}</strong></div><div><span>Financial component</span><strong>{a.financialComponent}</strong></div></div><p className="formula-band">{a.formula}</p><p>{a.example}</p></div>
  <section className="scenario-panel" aria-labelledby="energy-meaning"><p className="eyebrow">01 · Establish the meaning</p><h3 id="energy-meaning">What does a lower ratio mean?</h3><p>{a.summary}</p><p><strong>The decision to prepare</strong><br/>{a.decision}</p></section>
  <section className="prepared-section"><p className="eyebrow">02 · Assess the metric</p><h3>The nine-attribute assessment</h3><p>Read each classification with its conditions. The nine attributes are not combined into an overall score.</p><div className="score-grid">{attributes.map(attr=>{const p=a.attributes[attr.id];return <article className="score-card" key={attr.id}><h4>{attr.name}</h4><strong className="score-value">{p.classification}</strong><p className="score-condition">{p.reasoning}</p></article>})}</div></section>
  <section className="prepared-section"><p className="eyebrow">03 · Find what could change the decision</p><h3>Potential conflict map</h3><p>These are issues to investigate, not established disagreements. Your participants can confirm agreement, supply evidence or record a resolution.</p>
  {Object.values(result.submittedFeedback||{}).some(v=>v.trim())&&<details className="simple-details"><summary>Feedback supplied for discussion</summary><div className="role-feedback">{roles.map(([key,name])=><div key={key}><strong>{name}</strong><p>{result.submittedFeedback?.[key]||'No feedback supplied.'}</p></div>)}</div></details>}
  <div className="conflict-cards">{a.conflicts.map((c,i)=><article className="friction-card" key={c.title}><span className="research-tag">{['Clarification needed','Responsibility to assign','Evidence needed'][i]}</span><h4>{c.title}</h4><div className="dimension-tags">{c.attributeIds.map(id=><span key={id}>{attributes.find(attr=>attr.id===id)?.name}</span>)}</div><p><strong>Why it matters</strong><br/>{c.reasoning}</p><p className="ai-meta">Illustrative role feedback</p><div className="role-feedback">{roles.map(([key,name])=><div key={key}><strong>{name}</strong><p>{c[key]}</p></div>)}</div><div className="solution-box"><h5>Proposed resolution</h5><p>{c.solution}</p><h5>Translate this into an agenda item</h5><p>{c.agenda}</p><h5>Expected meeting output</h5><p>{c.expectedOutcome}</p></div><label>Record evidence, agreement or a resolution<textarea value={resolved[i]?.note||''} onChange={e=>setResolved(prev=>({...prev,[i]:{note:e.target.value,done:e.target.value.trim()?prev[i]?.done:false}}))}/></label><label className="resolve-check"><input type="checkbox" disabled={!resolved[i]?.note?.trim()} checked={!!resolved[i]?.done} onChange={e=>setResolved(prev=>({...prev,[i]:{...prev[i],done:e.target.checked}}))}/>Mark resolved</label></article>)}</div></section>
  <section className="prepared-section"><p className="eyebrow">04 · Prepare the meeting</p><h3>Your open agenda</h3><p>Each item follows from an unresolved issue above. Record a resolution to remove it from the open agenda and retain your note in the download.</p><ol className="prepared-agenda">{a.conflicts.map((c,i)=>!resolved[i]?.done&&<li key={c.title}><strong>{c.agenda}</strong><p>Proposed lead · {c.lead}</p><p>{c.expectedOutcome}</p><small>From the issue “{c.title}”</small></li>)}</ol>{a.conflicts.every((_,i)=>resolved[i]?.done)&&<p>All listed issues have recorded resolutions. This does not establish that the metric is valid.</p>}<button className="button primary" onClick={onDownload}>Download assessment & agenda ↓</button></section>
  <details className="prepared-section"><summary>Research evidence and limits</summary><p>This example uses a fixed, prewritten assessment rather than live AI generation. Its classifications, role feedback and proposed resolutions are illustrative, not validated findings. No interview evidence is cited.</p><p>Company feedback is retained as supplied for discussion and included in the download; it has not been analysed and does not change this example. Entries and resolutions remain on this page until it is reloaded. Download to keep a copy.</p></details>
 </div>;
}
