'use client';
import {useState} from 'react';
import {eps,epsProfile,epsIssues} from '../lib/eps-case';
import {attributes} from '../lib/metric-data';
import AIReview from './AIReview';
const scenarios={
 shadow:{name:'Internal shadow price',meaning:'An internal value used to explore carbon exposure in decisions. The adjustment is not necessarily a cash expense.',decision:'Decide how the internal adjustment should influence investment screening.',check:'Who selected the price, and would a different plausible price change the decision?',changes:{accuracy:'Construct fit needs confirmation',transparency:'Customized · rationale required'},agenda:'Agree the purpose of the shadow price and how much weight the adjusted EPS should carry.',outcome:'A documented internal decision rule and a price sensitivity check.'},
 expense:{name:'Expected emissions-related expense',meaning:'An estimate of an expense the company expects to bear. Coverage, timing and any amounts already included in net income must be reconciled.',decision:'Decide whether the adjustment adds information about expected financial exposure.',check:'Is any of this expense already deducted in net income, and do emissions and price cover the same activities?',changes:{accuracy:'Expense coverage needs confirmation',complexity:'Baseline low · reassess reconciliation',time:'Potential mixed periods · check timing'},agenda:'Reconcile expected carbon expense with net income and confirm coverage and timing before deducting it.',outcome:'A reconciliation that avoids double counting, or a decision to revise the formula.'},
 environmental:{name:'Estimated environmental cost',meaning:'A monetary valuation of environmental consequences. It need not represent an expense paid by the company.',decision:'Decide how environmental consequences should inform evaluation alongside financial earnings.',check:'Which environmental consequences does the valuation capture, and what remains outside it?',changes:{accuracy:'Valuation fit needs confirmation',complexity:'Baseline low · reassess valuation',transparency:'Customized · valuation method required'},agenda:'Agree what the environmental valuation represents and how it will inform the decision alongside financial earnings.',outcome:'A stated valuation boundary, limitations and decision rule.'}
};
export default function PreparedReview(){
 const [choice,setChoice]=useState('shadow'),[notes,setNotes]=useState({}),[done,setDone]=useState({});const s=scenarios[choice];
 const issues=epsIssues.map((issue,i)=>({...issue,question:i===0?s.agenda:issue.question,output:i===0?s.outcome:issue.output}));
 const key=id=>`${choice}-${id}`;
 function download(){const text=['METRIC LAB · PREPARED EPS REVIEW',s.name,s.meaning,s.decision,'Prepared scenario proposals; researcher review pending.',eps.formula,'NINE-ATTRIBUTE BASELINE',...epsProfile.map(p=>`${attributes.find(a=>a.id===p.id)?.name}: ${p.value}\nCondition: ${p.assumption}\nScenario implication: ${s.changes[p.id]||'Baseline retained conditionally; no additional change proposed.'}`),'OPEN AGENDA',...issues.filter(i=>!done[key(i.id)]).map(i=>`${i.question}\nIntended outcome: ${i.output}\nNote: ${notes[key(i.id)]||'None'}`),'RECORDED RESOLUTIONS',...issues.filter(i=>done[key(i.id)]).map(i=>`${i.title}\n${notes[key(i.id)]}`)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='Metric-Lab-EPS-Review.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="prepared-review">
 <AIReview customOnly/>
 <details className="prepared-section"><summary>Research, evidence and limits</summary><p>Dounia supplied the nine-attribute framework and conditional EPS baseline. Time orientation and additional verification questions are proposed extensions. The scenario implications and managerial prompts are prepared hypotheses awaiting her review.</p><p>No interview evidence is cited for these prepared scenarios. The custom AI implementation receives the framework, baseline and 99 de-identified analytical paraphrases from 33 coding summaries. It proposes interpretations, not validated predictions. Source identifiers are checked, but citation relevance requires human review.</p><p>Human participants establish whether the assumptions and evidence apply to their company. Consistency alone does not establish accuracy; a disclosed price alone does not establish methodological robustness.</p></details>
 <div className="prepared-section"><p className="eyebrow">Worked example</p><h3>Need a guide? Start with carbon-adjusted EPS.</h3><p>Follow the example below to see how an assessment leads to questions and a meeting agenda.</p></div>
 <div className="prepared-intro"><span className="research-tag">Prepared example · works without AI access</span><h3>{eps.name}</h3><p>{eps.definition}</p><div className="component-pair"><div><span>Sustainability component</span><strong>{eps.sustainability}</strong></div><div><span>Financial component</span><strong>{eps.financial}</strong></div></div><p className="formula-band">{eps.formula}</p></div>
 <section className="scenario-panel" aria-labelledby="scenario-title"><p className="eyebrow">01 · Establish the meaning</p><h3 id="scenario-title">What does the carbon price represent?</h3><p>The same arithmetic can express different claims. Choose an interpretation to examine its consequences.</p><div className="scenario-options">{Object.entries(scenarios).map(([id,v])=><button key={id} aria-pressed={choice===id} onClick={()=>setChoice(id)}>{v.name}</button>)}</div><div aria-live="polite"><h4>{s.meaning}</h4><p><strong>The decision to prepare</strong><br/>{s.decision}</p><p><strong>Ask before using the result</strong><br/>{s.check}</p></div></section>
 <section className="prepared-section"><p className="eyebrow">02 · Assess the metric</p><h3>The nine-attribute assessment</h3><p>Read each classification with its conditions. Notes refer to the carbon-price interpretation you selected above. The nine attributes are not combined into an overall score.</p><div className="score-grid">{epsProfile.map(p=><article className="score-card" key={p.id}><h4>{attributes.find(a=>a.id===p.id)?.name}</h4><strong className="score-value">{p.value}</strong><p className="score-condition">{p.assumption}</p>{s.changes[p.id]&&<p className="scenario-change"><strong>With {s.name.toLowerCase()}</strong><br/>{s.changes[p.id]}</p>}</article>)}</div></section>
 <section className="prepared-section"><p className="eyebrow">03 · Find what could change the decision</p><h3>Potential conflict map</h3><p>These are issues to investigate, not established disagreements. Your participants can confirm agreement, supply evidence or record a resolution.</p><div className="conflict-cards">{issues.map(i=><article className="friction-card" key={i.id}><span className="research-tag">{i.kind}</span><h4>{i.title}</h4><div className="dimension-tags">{i.attrs.map(id=><span key={id}>{attributes.find(a=>a.id===id)?.name}</span>)}</div><details className="simple-details"><summary>Why these attributes matter</summary>{i.attrs.map(id=><p key={id}><strong>{attributes.find(a=>a.id===id)?.name}</strong><br/>{({complexity:"A simple formula can still require difficult choices about valuation and how emissions relate to earnings.",transparency:"Can the team explain the method, boundaries and carbon-price choice?",accuracy:"Does the adjustment measure the financial or environmental meaning the team intends?",control:"Which parts of the result can each team influence?",impact:"How directly, and how soon, can actions affect the result?",reliability:"Are methods and boundaries consistent across reporting periods?",cost:"What additional data, staff time or expenditure does this assessment require?"})[id]}</p>)}</details><p><strong>Why it matters</strong><br/>{i.why}</p><p><strong>Decision or clarification needed</strong><br/>{i.question}</p><p><strong>Intended outcome</strong><br/>{i.output}</p><p className="ai-meta">Illustrative feedback · prepared for this example</p><div className="role-feedback">{i.positions.map((p,n)=><div key={n}><strong>{['CFO','Sustainability manager','Operations department'][n]}</strong><p>{p}</p></div>)}</div><div className="solution-box"><h5>Proposed resolution</h5><p>{i.question}</p><h5>Expected meeting output</h5><p>{i.output}</p><p>This proposal becomes an open agenda item below until your team records a resolution.</p></div><label>Record evidence, agreement or a resolution<textarea value={notes[key(i.id)]||''} onChange={e=>{setNotes({...notes,[key(i.id)]:e.target.value});if(!e.target.value.trim())setDone({...done,[key(i.id)]:false})}}/></label><label className="resolve-check"><input type="checkbox" disabled={!notes[key(i.id)]?.trim()} checked={!!done[key(i.id)]} onChange={e=>setDone({...done,[key(i.id)]:e.target.checked})}/>Resolved for this interpretation</label></article>)}</div></section>
 <section className="prepared-section"><p className="eyebrow">04 · Prepare the meeting</p><h3>Your open agenda</h3><p>Each item follows from an unresolved issue above. Notes and resolutions are kept separately for each carbon-price interpretation while this page stays open.</p><ol className="prepared-agenda">{issues.filter(i=>!done[key(i.id)]).map(i=><li key={i.id}><strong>{i.question}</strong><p>{i.output}</p><small>From the issue “{i.title}”</small></li>)}</ol>{issues.every(i=>done[key(i.id)])&&<p>All listed issues have recorded resolutions. This does not establish that the metric is valid.</p>}<button className="button primary" onClick={download}>Download assessment & agenda ↓</button></section>

 </div>
}
